CREATE TABLE classes (
    id BIGSERIAL PRIMARY KEY,
    name VARCHAR(150) NOT NULL,
    join_code VARCHAR(32) NOT NULL UNIQUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);